[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sktorch"
version = "0.1.0"
requires-python = ">=3.10"

# Add runtime deps that your package imports at import-time.
dependencies = [
  "numpy",
  "scikit-learn",
  "torch",
  "typing-extensions; python_version < '3.11'",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
optuna = ["optuna"] # will implement OptunaSearchCV later
test = ["pytest"]
dev = ["pytest", "ruff", "build", "twine"]
